Basic hero block. Simple feature block
inkOfPixel/inkofpixel.com pull request #128
Opened 2021-06-23 08:39 UTC by BaggioGiacomo

Created and styled hero and feature blocks. Added media queries to make them responsive.

2021-06-23 08:54 UTC, dhmacs requested changes
The editing view should have the same look and feel of the static view

2021-06-29 16:54 UTC, dhmacs commented
@BaggioGiacomo How do I get the home page up and running? It seems that the catch all route is defined as `[...slug]` instead of `[[...slug]]`, so the path `/` would just returns a 404 page 🤔

2021-07-01 06:56 UTC, dhmacs commented
@BaggioGiacomo 
Things to be fixed:

- [ ] Resolve all ESLint warnings
- [ ] Resolve ALL typescript errors (run `npm run build` to make sure that the code compile correctly... Later we will add this check directly as a Github Action)
- [ ] Fix wrong focus ring offset on feature section
- [ ] Remove nested block from hero section, keep it simple
- [ ] Force light mode for now (we'll address dark mode later if we have time to do it)

2021-07-09 07:49 UTC, dhmacs requested changes
We're almost there.. Just a few small fixes to be done 👍 

Make sure to remove also all unnecessary curly brackets from component props

2021-07-09 07:49 UTC, dhmacs commented on frontend/components/Splash.tsx
> +export default function Splash() {
What's the meaning of this component?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
> +    blocks?: CardBlockData[];
Why can block be undefined? Isn't it better to always make sure that blocks are defined (an empty array when there are no blocks) ?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureSectionBlock.tsx
> +export function FeatureSectionBlock(section: any, preview: boolean) {
- This is not how React components work, you should pass a props object, not a list of arguments
- rename this to `FeatureListSectionBlock` and refactor also all other name/types accordingly

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureSectionBlock.tsx
> +import { BlockItemProps, FEAT_BLOCK } from "@features/sectionBlocks";
Don't abbreviate `FEAT_BLOCK`, just use `FEATURE_BLOCK`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureSectionBlock.tsx
> +      <FeatureSectionBlock section={data} {...data} />
Why are we passing `data` to the section prop, and then we're spreading data as props ? It's like passing data to the component twice

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/index.ts
> +export const SECTION_PAGE_BLOCKS = {
I think this name should be the other way around: `PAGE_SECTION_BLOCKS`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/index.ts
> +export type SectionBlockData =
This should probably match the name of the exported `const`, that is `PageSectionBlockData`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/pageBlocks/types.ts
> +export type SectionBlockTemplateData<TemplateName, Type> = {
Why has this type been renamed? It's supposed to be generic right? It should be possible to use it to declare the data type of any block, not just sections, right?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/plugins/usePagePlugin.ts
> +import { assertNever } from "utils";
This should not be imported this way. It should be like

```typescript
import { assertNever } from "@utils";
```

You need to customize `tsconfig.json` in order to enable it

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/plugins/usePagePlugin.ts
>      initialValues: pageData,
What's `label: "aa"` ? Can we use something like `"Page"` here?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/plugins/usePagePlugin.ts
> +                }
Here we should filter out null values from the blocks array before doing the map

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/plugins/usePagePlugin.ts
> +              }),
Same as above, remove null blocks. Remove also the console.log

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/CardBlock.tsx
> +      <CardBlock {...data} projectLink={data.projectLink} />
`projectLink={data.projectLink}` is redundant, since we're already spreading `data` as props, so why are we doing it?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +    serviceLink: Nullable<string>;
I think this field name should be `featureLink`. But I'd like to simplify this further and rename it to `url`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +  serviceLink?: string;
same as above, just rename it to `url`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +                return imageSrc;
clean up the comments

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +        id: "51",
What's this hard-coded magic id?

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +      serviceLink: "/",
same as above, rename it to `url`

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +    label: "feat",
Use the full name, `Feature` (I think we want it to be uppercase)

2021-07-09 07:49 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +        name: "serviceLink",
same as above, `url`

2021-07-09 07:49 UTC, dhmacs commented on frontend/graphql/GetPages.graphql
> +          projectLink
Why `projectLink`? If we make the data component generic, we shouldn't encode specific use cases as names for the field... I'd put just `url`

2021-07-09 07:49 UTC, dhmacs commented on frontend/layouts/defaultLayout/index.tsx
> +        </Flex>*/}
Just drop comments

2021-07-09 07:49 UTC, dhmacs commented on frontend/pages/_document.tsx
> +        <body style={{ overflowX: "hidden" }}>
This style looks suspicious... Content shouldn't overflow, and if it does, it should be fixed. Is there a specific reason why we're using this?

2021-07-09 07:49 UTC, dhmacs commented on frontend/pages/_index.tsx
>  export default function HomePage() {
Can we drop this page?

2021-07-09 07:49 UTC, dhmacs commented on frontend/theme/index.ts
>  });
If these are default Chakra breakpoints, we can remove this override

2021-07-09 07:49 UTC, dhmacs commented on frontend/tsconfig.json
> +    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "@types/index.d.ts", "next.config.js"]
why is `next.config.js` included here?

2021-07-09 14:27 UTC, BaggioGiacomo commented
Fixed 👍🏻

2021-07-12 07:01 UTC, dhmacs requested changes
I've added a few things to correct

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
> +      sectionTitle: "OUR WORK",
This should probably default to something like "Default section title"

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
> +      </Box>
It seems that this condition is useless, as both branches render the same exact thing

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
>      label: "cardSection",
Since this is a label that should be read by the content editor, I think we should write it like `Card List Section`

Also the name of the of the component should be something like `CardListSectionBlock`

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
>        blocks: [],
Add a couple of default blocks so that the default new section looks nicer

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/CardSectionBlock.tsx
> -import { Box } from "@chakra-ui/react";
The components styles are a little bit odd, and the focus ring seems a little bit translated.
Also cards should not be too thin, it's better to keep them larger than trying to squeeze them into one row

<img width="320" alt="Screen Shot 2021-07-12 at 08 36 09" src="https://user-images.githubusercontent.com/4640135/125242085-90892b80-e2ec-11eb-8f54-141cdb9d995a.png">

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureListSectionBlock.tsx
> +    <Box as="section" pb={"36"}>
remove curly brackets here

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureListSectionBlock.tsx
> +        {sectionTitle != null ? (
Whenever possible try to formulate conditions that avoid logical not.. For example here the two branches can be reversed with the condition `== null`

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureListSectionBlock.tsx
> +      sectionTitle: "SERVICES",
Do not use use-case specific default values here, use something like `Section title`

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureListSectionBlock.tsx
>      label: "featureSection",
This label is read by the content editor, it should be "Feature Section", or  "Feature List Section" to be more descriptive

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/pageBlocks/FeatureListSectionBlock.tsx
>        blocks: [],
Add a few default blocks to make the section look nice when is newly created

2021-07-12 07:01 UTC, dhmacs commented on frontend/features/sectionBlocks/FeatureBlock.tsx
> +    label: "FEATURE",
This should not be uppercase

2021-07-12 07:01 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
>                        title: feature.title ? feature.title : null,
a way to make this shorter is `title: feature.title || null`

2021-07-12 07:01 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
> +                        url: card.url ? card.url : null,
You can make this shorter, as mentioned in above comment

2021-07-12 07:54 UTC, BaggioGiacomo commented on frontend/features/pageBlocks/CardSectionBlock.tsx
> -import { Box } from "@chakra-ui/react";
Fixed by removing margin and fixed height

2021-07-12 08:34 UTC, BaggioGiacomo commented
Fixed all

2021-07-12 13:34 UTC, dhmacs requested changes
It's coming home!

2021-07-12 13:34 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
>      <div>
Can we remove this?

2021-07-12 13:34 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
> +                        url: card.url ? card.url : null,
@BaggioGiacomo ❗

2021-07-12 13:46 UTC, BaggioGiacomo commented
I think we're ready to merge 💯

2021-07-12 13:51 UTC, dhmacs approved these changes
👍

2021-07-12 13:51 UTC, merged