Add footer section
inkOfPixel/inkofpixel.com pull request #151
Opened 2021-07-15 08:23 UTC by BaggioGiacomo

2021-08-26 15:20 UTC, dhmacs requested changes
The footer model needs to be revised, since right now it's using a collection type, where as its data can just be modeled as a single type. In fact, there's no need to define a "footer" model, as all data that the footer contains, can be considered as generic, reusable data, to be put under the "Global" model..
Here's a few global settings that are used by the footer:

- Company legal name
- Primary email
- VAT ID
- Capital
- Additional legal info 
- Locations

Note that the description next to the logo in the footer is probably the only piece of data that is specific to the footer. This can still be added under global settings, in a section dedicated to contain footer data

2021-08-30 08:12 UTC, dhmacs requested changes
While I edit content on the side bar, the footer content does not update in realtime

2021-08-31 08:35 UTC, dhmacs requested changes
I think we want to simplify the footer by removing unnecessary abstractions like `UpperFooter` and `LowerFooter`.. Here's what it would look like more or less

```tsx
<Footer>
  <Flex>
    <FooterHomeLink>
      <WordmarkLogo />
    </FooterHomeLink>
    <VStack>
      <FooterDescription>{...}</FooterDescription>
      <FooterPrimaryEmail>{...}</FooterPrimaryEmail>
      <LocationBlocks />
    </VStack>
  </Flex>
  <VStack>
    <Copyright>{...}</Copyright>
    <LegalCopy>{...}</LegalCopy>
  </VStack>
</Footer>
```

2021-08-31 08:35 UTC, dhmacs commented on frontend/components/AppProviders.tsx
> +          position: "overlay",
Let's keep the default behavior "displace". The navigation bar overflows the page when the page is displaced, see if you can find a quick fix for that, otherwise we're gonna merge anyway for now, and create an issue for the navigation bar responsive bug

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +};
This is unused, let's get rid of it

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      fontFamily="Roboto Mono"
Since "Roboto Mono" is the default font for the page, let's define it on the body (or at page level) and get rid on this line

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      letterSpacing="0.08em"
Letter spacing for default text should be defined at global level, like the font. (it should be 0.02em according to the production website)

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      overflow="hidden"
Probably don't need these

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      pt="36"
`pt` and `pb` can be summarized with `py`

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      as="section">
The footer semantically is not a "section", but indeed it's a "footer"

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +        }}
These can be summarized into a `px`

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +          xl: "1200px",
Can we use the container token when we have these default container sizes? It would make it easier to customize these sizes everywhere in the page

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +        pos="relative"
Do we need this?

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +        letterSpacing="0.02em">
Get rid of this, should be globally defined

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/blocks/FooterBlock.tsx
> +export function FooterBlock({
This name is too generic, and pretty much meaningless... This refers to locations blocks, so you should renamed it to reflect this fact. Don't forget to rename everything else too (e.g. props, blocks labels, etc)

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/Footer/index.ts
> +export const FOOTER_BLOCK = {
Same consideration as above about the naming

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/page/sections/CardListSection/CardListSectionBlock.tsx
> +      backgroundColor="cardSectionBg"
Define this color as `emerald.50`

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/page/sections/CardListSection/CardListSectionBlock.tsx
> +        letterSpacing="0.02em"
Letter spacing should be globally defined for default text

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/page/sections/CardListSection/CardListSectionBlock.tsx
> +          letterSpacing="0.02em"
Letter spacing should be globally defined for default text

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/page/sections/FeatureListSection/FeatureListSectionBlock.tsx
> +              letterSpacing="0.02em"
Letter spacing should be globally defined for default text

2021-08-31 08:35 UTC, dhmacs commented on frontend/features/page/sections/FeatureListSection/FeatureListSectionBlock.tsx
> +              fontFamily="Roboto Mono"
font family should be globally defined for default text

2021-08-31 12:27 UTC, BaggioGiacomo commented on frontend/components/AppProviders.tsx
> +          position: "overlay",
Let's create an issue, there's a few to do to fix it

2021-08-31 14:49 UTC, dhmacs requested changes

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +export function LegalInfo({ company }: LegalInfoProps) {
This can be removed, and its implementation placed directly in the slug page

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      className="caption"
remove?

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      fontSize="sm"
Is this needed?

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +            transition: "all 300ms ease 0s",
Seems like `0s` is redundant

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/Footer/Footer.tsx
> +      fontSize="sm"
Is this really needed? I guess it's not

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/mainNavigation/index.tsx
> +      }
remove this, we'll address this in another issue

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/page/sections/CardListSection/blocks/CardBlock.tsx
> +          <Box lineHeight="1.6em" color="cardDescription" name="description">
let's rename the color token to be `subduedText`

2021-08-31 14:49 UTC, dhmacs commented on frontend/features/page/sections/FeatureListSection/blocks/FeatureBlock.tsx
> +          <Box fontWeight="subtitle" lineHeight="subtitle" color="description">
rename this `subduedText`

2021-08-31 14:49 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
> +            <LegalInfo company={values.global.companyData}></LegalInfo>
replace this with a simple Text

2021-08-31 14:49 UTC, dhmacs commented on frontend/pages/[[...slug]].tsx
> +} from "@features/Footer/Footer";
refactor folder, import should be `"@features/Footer"`

2021-08-31 14:49 UTC, dhmacs commented on frontend/pages/_document.tsx
> +          }}
These should be defined into `theme.styles.global`, not here

2021-08-31 14:49 UTC, dhmacs commented on frontend/plugins/usePagePlugin.ts
> +function getFooterInput(data: GlobalData): UpdateGlobalInput {
`Footer` is a view concern that should interfere with data... Here we're not getting "footer" input, we're getting "global settings" input

2021-08-31 14:49 UTC, dhmacs commented on frontend/theme/index.ts
> +      300: "#4FD1C5",
this should be `500` not `300`

2021-08-31 14:49 UTC, dhmacs commented on frontend/theme/index.ts
>      description: "rgb(92,92,92)",
this should be `subduedText`.. Remember to rename it everywhere you've used it

2021-09-01 10:13 UTC, dhmacs requested changes

2021-09-01 10:13 UTC, dhmacs commented on frontend/features/mainNavigation/index.tsx
> +        <Box as="a" href={router.locale} ml="1" mb="8">
remove `href` attribute, it's already received from NextLink

2021-09-01 10:13 UTC, dhmacs commented on frontend/features/page/sections/ContactsSection/ContactsSection.tsx
> +                color="subdudeText"
`subduedText`

2021-09-01 10:13 UTC, dhmacs commented on frontend/features/page/sections/FeatureListSection/FeatureListSectionBlock.tsx
> +    <Box as="section" pt={index === 0 ? "44" : "0"}>
?

2021-09-01 10:13 UTC, dhmacs commented on frontend/theme/index.ts
> +    subdudeText: "#5C5C5C",
`subduedText`

2021-09-01 14:38 UTC, BaggioGiacomo commented on frontend/theme/index.ts
> +    subdudeText: "#5C5C5C",
😂

2021-09-02 06:54 UTC, dhmacs approved these changes

2021-09-02 07:04 UTC, merged